/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                    'rgb(var(--c-primary) / <alpha-value>)',
        'on-primary':                 'rgb(var(--c-on-primary) / <alpha-value>)',
        'primary-container':          'rgb(var(--c-primary-container) / <alpha-value>)',
        'on-primary-container':       'rgb(var(--c-on-primary-container) / <alpha-value>)',
        'inverse-primary':            'rgb(var(--c-inverse-primary) / <alpha-value>)',
        'secondary':                  'rgb(var(--c-secondary) / <alpha-value>)',
        'on-secondary':               'rgb(var(--c-on-secondary) / <alpha-value>)',
        'secondary-container':        'rgb(var(--c-secondary-container) / <alpha-value>)',
        'on-secondary-container':     'rgb(var(--c-on-secondary-container) / <alpha-value>)',
        'tertiary':                   'rgb(var(--c-tertiary) / <alpha-value>)',
        'on-tertiary':                'rgb(var(--c-on-tertiary) / <alpha-value>)',
        'tertiary-container':         'rgb(var(--c-tertiary-container) / <alpha-value>)',
        'on-tertiary-container':      'rgb(var(--c-on-tertiary-container) / <alpha-value>)',
        'error':                      'rgb(var(--c-error) / <alpha-value>)',
        'on-error':                   'rgb(var(--c-on-error) / <alpha-value>)',
        'error-container':            'rgb(var(--c-error-container) / <alpha-value>)',
        'on-error-container':         'rgb(var(--c-on-error-container) / <alpha-value>)',
        'background':                 'rgb(var(--c-background) / <alpha-value>)',
        'on-background':              'rgb(var(--c-on-background) / <alpha-value>)',
        'surface':                    'rgb(var(--c-surface) / <alpha-value>)',
        'surface-dim':                'rgb(var(--c-surface-dim) / <alpha-value>)',
        'surface-bright':             'rgb(var(--c-surface-bright) / <alpha-value>)',
        'surface-container-lowest':   'rgb(var(--c-surface-container-lowest) / <alpha-value>)',
        'surface-container-low':      'rgb(var(--c-surface-container-low) / <alpha-value>)',
        'surface-container':          'rgb(var(--c-surface-container) / <alpha-value>)',
        'surface-container-high':     'rgb(var(--c-surface-container-high) / <alpha-value>)',
        'surface-container-highest':  'rgb(var(--c-surface-container-highest) / <alpha-value>)',
        'surface-variant':            'rgb(var(--c-surface-variant) / <alpha-value>)',
        'surface-tint':               'rgb(var(--c-surface-tint) / <alpha-value>)',
        'on-surface':                 'rgb(var(--c-on-surface) / <alpha-value>)',
        'on-surface-variant':         'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        'inverse-surface':            'rgb(var(--c-inverse-surface) / <alpha-value>)',
        'inverse-on-surface':         'rgb(var(--c-inverse-on-surface) / <alpha-value>)',
        'outline':                    'rgb(var(--c-outline) / <alpha-value>)',
        'outline-variant':            'rgb(var(--c-outline-variant) / <alpha-value>)',
        // Semantic category colors (fixed — work in both themes)
        'note-pink': '#ec4899',
        'task-amber': '#f59e0b',
        'finance-cyan': '#06b6d4',
        'habit-green': '#10b981',
      },
      fontFamily: {
        'manrope': ['Manrope', 'sans-serif'],
        'work-sans': ['Work Sans', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
        'h1': ['Manrope', 'sans-serif'],
        'h2': ['Manrope', 'sans-serif'],
        'h3': ['Manrope', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'mono': ['Inter', 'monospace'],
      },
      fontSize: {
        'h1': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3': ['24px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.04em', fontWeight: '600' }],
        'mono': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '12px',
        'base': '8px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
        'margin': '32px',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.06), 0 4px 12px rgba(0,0,0,0.09)',
        'card-hover': '0 4px 8px rgba(0,0,0,0.08), 0 8px 24px rgba(0,0,0,0.12)',
        'modal': '0 20px 60px rgba(0,0,0,0.18)',
        'nav': '0 -2px 8px rgba(0,0,0,0.08)',
        'fab': '0 8px 24px rgba(0,74,198,0.35)',
      },
      animation: {
        'slide-up': 'slideUp 0.3s cubic-bezier(0.16,1,0.3,1)',
        'fade-in': 'fadeIn 0.2s ease-out',
        'scale-in': 'scaleIn 0.2s cubic-bezier(0.16,1,0.3,1)',
      },
      keyframes: {
        slideUp: {
          from: { transform: 'translateY(100%)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        scaleIn: {
          from: { transform: 'scale(0.95)', opacity: '0' },
          to: { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
